services:
  vamtyc-db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "vamtyc"
    volumes:
      - "dbdata:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
volumes:
  dbdata: {}
