@base-url=http://localhost:3000

###

GET {{base-url}}/Resource

###

# @name create
POST {{base-url}}/Resource
Content-Type: application/json

{
    "name": [{
        "given": ["John"],
        "family": "Doe"
    }],
    "gender": "male"
}

###

GET {{base-url}}/Resource/{{create.response.body.id}}

###

DELETE {{base-url}}/Resource/{{create.response.body.id}}

###

PUT {{base-url}}/Resource/{{create.response.body.id}}
Content-Type: application/json

{
    "name": [{
        "given": ["John", "Martin"],
        "family": "Doe"
    }],
    "gender": "male"
}

###


POST {{base-url}}/Transaction
Content-Type: application/json

{
    "resouceType": "Transaction",
    "items": [{
        "resourceType": "HttpRequest",
        "method": "POST",
        "url": "/Resource",
        "body": {
            "name": [{
                "given": ["John"],
                "family": "Doe"
            }],
            "gender": "male"
        }
    }]
}

###

POST {{base-url}}/Transaction

{
    "resourceType": "Transaction",
    "items": [{
        "resourceType": "HttpRequest",
        "method": "DELETE",
        "url": "/Resource/33a7d4be-f33d-44b1-8783-faf2277b6b2f"
    }, {
        "resourceType": "HttpRequest",
        "method": "DELETE",
        "url": "/Resource/10bc01cc-7da1-4749-a835-12b308f165c1"
    }]
}

###

PUT {{base-url}}/Queryp/e985388c-da0a-4409-bf52-e1f4c08374a9
Content-Type: application/json

{
    "code": "/Coding/core-queryps?code=text",
    "desc": "Filter Route by res-type",
    "name": "res-type",
    "type": "Route",
    "path": [
        { "name": "path", "collection": true },
        { "name": "value" }
    ],
    "queryparams": "/Queryp"
}

###

GET {{base-url}}/Queryp/b8b34356-f18d-4486-b48b-58a3aab40772
