GET http://localhost:3000/Resource

###

# @name create
POST http://localhost:3000/Resource
Content-Type: application/json

{
    "name": [{
        "given": ["John"],
        "family": "Doe"
    }],
    "gender": "male"
}

###

GET http://localhost:3000/Resource/{{create.response.body.id}}

###

DELETE http://localhost:3000/Resource/{{create.response.body.id}}

###

PUT http://localhost:3000/Resource/{{create.response.body.id}}
Content-Type: application/json

{
    "name": [{
        "given": ["John", "Martin"],
        "family": "Doe"
    }],
    "gender": "male"
}

###


POST http://localhost:3000/Transaction
Content-Type: application/json

{
    "resouceType": "Transaction",
    "items": [{
        "resourceType": "HttpRequest",
        "method": "POST",
        "url": "/Resource",
        "body": {
            "name": [{
                "given": ["John"],
                "family": "Doe"
            }],
            "gender": "male"
        }
    }]
}

###

POST http://localhost:3000/Transaction

{
    "resourceType": "Transaction",
    "items": [{
        "resourceType": "HttpRequest",
        "method": "DELETE",
        "url": "/Resource/33a7d4be-f33d-44b1-8783-faf2277b6b2f"
    }, {
        "resourceType": "HttpRequest",
        "method": "DELETE",
        "url": "/Resource/10bc01cc-7da1-4749-a835-12b308f165c1"
    }]
}